/// Comprehensive ISO 4217 World Currencies List with symbols, names, and flags.
class WorldCurrency {
  final String code;
  final String name;
  final String symbol;
  final String flag;

  const WorldCurrency({
    required this.code,
    required this.name,
    required this.symbol,
    required this.flag,
  });
}

const List<WorldCurrency> kWorldCurrencies = [
  WorldCurrency(code: 'USD', name: 'US Dollar', symbol: '\$', flag: '🇺🇸'),
  WorldCurrency(code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺'),
  WorldCurrency(code: 'GBP', name: 'British Pound', symbol: '£', flag: '🇬🇧'),
  WorldCurrency(code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', flag: '🇧🇩'),
  WorldCurrency(code: 'INR', name: 'Indian Rupee', symbol: '₹', flag: '🇮🇳'),
  WorldCurrency(code: 'CAD', name: 'Canadian Dollar', symbol: 'CA\$', flag: '🇨🇦'),
  WorldCurrency(code: 'AUD', name: 'Australian Dollar', symbol: 'AU\$', flag: '🇦🇺'),
  WorldCurrency(code: 'JPY', name: 'Japanese Yen', symbol: '¥', flag: '🇯🇵'),
  WorldCurrency(code: 'CNY', name: 'Chinese Yuan', symbol: '¥', flag: '🇨🇳'),
  WorldCurrency(code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', flag: '🇸🇦'),
  WorldCurrency(code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', flag: '🇦🇪'),
  WorldCurrency(code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', flag: '🇶🇦'),
  WorldCurrency(code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', flag: '🇰🇼'),
  WorldCurrency(code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', flag: '🇧🇭'),
  WorldCurrency(code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', flag: '🇴🇲'),
  WorldCurrency(code: 'SGD', name: 'Singapore Dollar', symbol: 'S\$', flag: '🇸🇬'),
  WorldCurrency(code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', flag: '🇲🇾'),
  WorldCurrency(code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', flag: '🇵🇰'),
  WorldCurrency(code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', flag: '🇱🇰'),
  WorldCurrency(code: 'NPR', name: 'Nepalese Rupee', symbol: 'रू', flag: '🇳🇵'),
  WorldCurrency(code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', flag: '🇨🇭'),
  WorldCurrency(code: 'SEK', name: 'Swedish Krona', symbol: 'kr', flag: '🇸🇪'),
  WorldCurrency(code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', flag: '🇳🇴'),
  WorldCurrency(code: 'DKK', name: 'Danish Krone', symbol: 'kr', flag: '🇩🇰'),
  WorldCurrency(code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ\$', flag: '🇳🇿'),
  WorldCurrency(code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK\$', flag: '🇭🇰'),
  WorldCurrency(code: 'KRW', name: 'South Korean Won', symbol: '₩', flag: '🇰🇷'),
  WorldCurrency(code: 'TRY', name: 'Turkish Lira', symbol: '₺', flag: '🇹🇷'),
  WorldCurrency(code: 'RUB', name: 'Russian Ruble', symbol: '₽', flag: '🇷🇺'),
  WorldCurrency(code: 'BRL', name: 'Brazilian Real', symbol: 'R\$', flag: '🇧🇷'),
  WorldCurrency(code: 'MXN', name: 'Mexican Peso', symbol: 'Mex\$', flag: '🇲🇽'),
  WorldCurrency(code: 'ZAR', name: 'South African Rand', symbol: 'R', flag: '🇿🇦'),
  WorldCurrency(code: 'NGN', name: 'Nigerian Naira', symbol: '₦', flag: '🇳🇬'),
  WorldCurrency(code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', flag: '🇪🇬'),
  WorldCurrency(code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', flag: '🇮🇩'),
  WorldCurrency(code: 'THB', name: 'Thai Baht', symbol: '฿', flag: '🇹🇭'),
  WorldCurrency(code: 'PHP', name: 'Philippine Peso', symbol: '₱', flag: '🇵🇭'),
  WorldCurrency(code: 'VND', name: 'Vietnamese Dong', symbol: '₫', flag: '🇻🇳'),
  WorldCurrency(code: 'PLN', name: 'Polish Zloty', symbol: 'zł', flag: '🇵🇱'),
  WorldCurrency(code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', flag: '🇨🇿'),
  WorldCurrency(code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', flag: '🇭🇺'),
  WorldCurrency(code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', flag: '🇮🇱'),
  WorldCurrency(code: 'CLP', name: 'Chilean Peso', symbol: 'CLP\$', flag: '🇨🇱'),
  WorldCurrency(code: 'COP', name: 'Colombian Peso', symbol: 'COL\$', flag: '🇨🇴'),
  WorldCurrency(code: 'ARS', name: 'Argentine Peso', symbol: '\$', flag: '🇦🇷'),
  WorldCurrency(code: 'PEN', name: 'Peruvian Sol', symbol: 'S/.', flag: '🇵🇪'),
  WorldCurrency(code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', flag: '🇰🇪'),
  WorldCurrency(code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', flag: '🇬🇭'),
  WorldCurrency(code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', flag: '🇹🇿'),
  WorldCurrency(code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', flag: '🇺🇬'),
  WorldCurrency(code: 'MAD', name: 'Moroccan Dirham', symbol: 'DH', flag: '🇲🇦'),
  WorldCurrency(code: 'DZD', name: 'Algerian Dinar', symbol: 'DA', flag: '🇩🇿'),
  WorldCurrency(code: 'TND', name: 'Tunisian Dinar', symbol: 'DT', flag: '🇹🇳'),
  WorldCurrency(code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD', flag: '🇯🇴'),
  WorldCurrency(code: 'LBN', name: 'Lebanese Pound', symbol: 'L£', flag: '🇱🇧'),
  WorldCurrency(code: 'IQD', name: 'Iraqi Dinar', symbol: 'ID', flag: '🇮🇶'),
  WorldCurrency(code: 'AFN', name: 'Afghan Afghani', symbol: '؋', flag: '🇦🇫'),
  WorldCurrency(code: 'ALL', name: 'Albanian Lek', symbol: 'L', flag: '🇦🇱'),
  WorldCurrency(code: 'AMD', name: 'Armenian Dram', symbol: '֏', flag: '🇦🇲'),
  WorldCurrency(code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', flag: '🇦🇴'),
  WorldCurrency(code: 'AWG', name: 'Aruban Florin', symbol: 'Afl.', flag: '🇦🇼'),
  WorldCurrency(code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', flag: '🇦🇿'),
  WorldCurrency(code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', flag: '🇧🇦'),
  WorldCurrency(code: 'BBD', name: 'Barbadian Dollar', symbol: 'Bds\$', flag: '🇧🇧'),
  WorldCurrency(code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', flag: '🇧🇮'),
  WorldCurrency(code: 'BMD', name: 'Bermudan Dollar', symbol: 'BD\$', flag: '🇧🇲'),
  WorldCurrency(code: 'BND', name: 'Brunei Dollar', symbol: 'B\$', flag: '🇧🇳'),
  WorldCurrency(code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', flag: '🇧🇴'),
  WorldCurrency(code: 'BSD', name: 'Bahamian Dollar', symbol: 'B\$', flag: '🇧🇸'),
  WorldCurrency(code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', flag: '🇧🇹'),
  WorldCurrency(code: 'BWP', name: 'Botswanan Pula', symbol: 'P', flag: '🇧🇼'),
  WorldCurrency(code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', flag: '🇧🇾'),
  WorldCurrency(code: 'BZD', name: 'Belize Dollar', symbol: 'BZ\$', flag: '🇧🇿'),
  WorldCurrency(code: 'CDF', name: 'Congolese Franc', symbol: 'FC', flag: '🇨🇩'),
  WorldCurrency(code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', flag: '🇨🇷'),
  WorldCurrency(code: 'CUP', name: 'Cuban Peso', symbol: '\$', flag: '🇨🇺'),
  WorldCurrency(code: 'CVE', name: 'Cape Verdean Escudo', symbol: 'Esc', flag: '🇨🇻'),
  WorldCurrency(code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', flag: '🇩🇯'),
  WorldCurrency(code: 'DOP', name: 'Dominican Peso', symbol: 'RD\$', flag: '🇩🇴'),
  WorldCurrency(code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', flag: '🇪🇷'),
  WorldCurrency(code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', flag: '🇪🇹'),
  WorldCurrency(code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ\$', flag: '🇫🇯'),
  WorldCurrency(code: 'GEL', name: 'Georgian Lari', symbol: '₾', flag: '🇬🇪'),
  WorldCurrency(code: 'GIP', name: 'Gibraltar Pound', symbol: '£', flag: '🇬🇮'),
  WorldCurrency(code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', flag: '🇬🇲'),
  WorldCurrency(code: 'GNF', name: 'Guinean Franc', symbol: 'FG', flag: '🇬🇳'),
  WorldCurrency(code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', flag: '🇬🇹'),
  WorldCurrency(code: 'GYD', name: 'Guyanaese Dollar', symbol: 'G\$', flag: '🇬🇾'),
  WorldCurrency(code: 'HNL', name: 'Honduran Lempira', symbol: 'L', flag: '🇭🇳'),
  WorldCurrency(code: 'HTG', name: 'Haitian Gourde', symbol: 'G', flag: '🇭🇹'),
  WorldCurrency(code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', flag: '🇮🇸'),
  WorldCurrency(code: 'JMD', name: 'Jamaican Dollar', symbol: 'J\$', flag: '🇯🇲'),
  WorldCurrency(code: 'KGS', name: 'Kyrgystani Som', symbol: 'с', flag: '🇰🇬'),
  WorldCurrency(code: 'KHR', name: 'Cambodian Riel', symbol: '៛', flag: '🇰🇭'),
  WorldCurrency(code: 'KMF', name: 'Comorian Franc', symbol: 'CF', flag: '🇰🇲'),
  WorldCurrency(code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', flag: '🇰🇿'),
  WorldCurrency(code: 'LAK', name: 'Laotian Kip', symbol: '₭', flag: '🇱🇦'),
  WorldCurrency(code: 'LRD', name: 'Liberian Dollar', symbol: 'L\$', flag: '🇱🇷'),
  WorldCurrency(code: 'LSL', name: 'Lesotho Loti', symbol: 'L', flag: '🇱🇸'),
  WorldCurrency(code: 'LYD', name: 'Libyan Dinar', symbol: 'LD', flag: '🇱🇾'),
  WorldCurrency(code: 'MDL', name: 'Moldovan Leu', symbol: 'L', flag: '🇲🇩'),
  WorldCurrency(code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', flag: '🇲🇬'),
  WorldCurrency(code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', flag: '🇲🇰'),
  WorldCurrency(code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', flag: '🇲🇲'),
  WorldCurrency(code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', flag: '🇲🇳'),
  WorldCurrency(code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP\$', flag: '🇲🇴'),
  WorldCurrency(code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', flag: '🇲🇷'),
  WorldCurrency(code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', flag: '🇲🇺'),
  WorldCurrency(code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', flag: '🇲🇻'),
  WorldCurrency(code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', flag: '🇲🇼'),
  WorldCurrency(code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', flag: '🇲🇿'),
  WorldCurrency(code: 'NAD', name: 'Namibian Dollar', symbol: 'N\$', flag: '🇳🇦'),
  WorldCurrency(code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C\$', flag: '🇳🇮'),
  WorldCurrency(code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', flag: '🇵🇦'),
  WorldCurrency(code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', flag: '🇵🇬'),
  WorldCurrency(code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', flag: '🇵🇾'),
  WorldCurrency(code: 'RSD', name: 'Serbian Dinar', symbol: 'din.', flag: '🇷🇸'),
  WorldCurrency(code: 'RWF', name: 'Rwandan Franc', symbol: 'RF', flag: '🇷🇼'),
  WorldCurrency(code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI\$', flag: '🇸🇧'),
  WorldCurrency(code: 'SCR', name: 'Seychellois Rupee', symbol: 'SR', flag: '🇸🇨'),
  WorldCurrency(code: 'SDG', name: 'Sudanese Pound', symbol: 'SDG', flag: '🇸🇩'),
  WorldCurrency(code: 'SOS', name: 'Somali Shilling', symbol: 'Ssh', flag: '🇸🇴'),
  WorldCurrency(code: 'SRD', name: 'Surinamese Dollar', symbol: 'Sr\$', flag: '🇸🇷'),
  WorldCurrency(code: 'SYP', name: 'Syrian Pound', symbol: 'S£', flag: '🇸🇾'),
  WorldCurrency(code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E', flag: '🇸🇿'),
  WorldCurrency(code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', flag: '🇹🇯'),
  WorldCurrency(code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', flag: '🇹🇲'),
  WorldCurrency(code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T\$', flag: '🇹🇴'),
  WorldCurrency(code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT\$', flag: '🇹🇹'),
  WorldCurrency(code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT\$', flag: '🇹🇼'),
  WorldCurrency(code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', flag: '🇺🇦'),
  WorldCurrency(code: 'UYU', name: 'Uruguayan Peso', symbol: '\$U', flag: '🇺🇾'),
  WorldCurrency(code: 'UZS', name: 'Uzbekistani Som', symbol: 'soʻm', flag: '🇺🇿'),
  WorldCurrency(code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.S', flag: '🇻🇪'),
  WorldCurrency(code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', flag: '🇻🇺'),
  WorldCurrency(code: 'WST', name: 'Samoan Tala', symbol: 'WS\$', flag: '🇼🇸'),
  WorldCurrency(code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', flag: '🇨🇲'),
  WorldCurrency(code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC\$', flag: '🇦🇬'),
  WorldCurrency(code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', flag: '🇸🇳'),
  WorldCurrency(code: 'XPF', name: 'CFP Franc', symbol: '₣', flag: '🇵🇫'),
  WorldCurrency(code: 'YER', name: 'Yemeni Rial', symbol: '﷼', flag: '🇾🇪'),
  WorldCurrency(code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', flag: '🇿🇲'),
  WorldCurrency(code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z\$', flag: '🇿🇼'),
];
