// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DefaultFirebaseOptions have not been configured for web');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOyokA9-Zr-3ImGKJORfb1k8-N7J07lL8',
    appId: '1:783558160918:android:b380ff4ac15fdc9f467b37',
    messagingSenderId: '783558160918',
    projectId: 'expense-tracker-1891b',
    storageBucket: 'expense-tracker-1891b.firebasestorage.app',
  );
}
