// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DefaultFirebaseOptions have not been configured for web');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'BNxTB0EoOk0bepc_fG5Q5nSxovdbYp8bTXoLZ8KuvndTVe1E0vm72Fd2MJt-STTEDAv5zXJJRP1GwGHD2dBAHp8',
    appId: '1:657477735157:android:6593dfe69c626f152d2bbc',
    messagingSenderId: '657477735157',
    projectId: 'expense-tracker-79ef7',
    storageBucket: 'expense-tracker-79ef7.firebasestorage.app',
  );
}
